#!/usr/bin/env python3
"""Generates every launcher asset from one geometry description.

Outputs:
  - android/.../drawable/ic_launcher_foreground.xml   (adaptive, vector)
  - android/.../drawable/ic_launcher_monochrome.xml   (themed icon, vector)
  - android/.../values/ic_launcher_background.xml     (flat colour)
  - android/.../mipmap-anydpi-v26/ic_launcher.xml     (adaptive wiring)
  - android/.../mipmap-*/ic_launcher.png              (legacy, API < 26)
  - tool/play_store_icon.png                          (512x512 listing icon)
  - tool/icon_preview.png                             (what a round mask shows)

The art: a white SIM card with the classic cut corner and a gold contact
chip, on a deep teal ground. Adaptive-icon safe zone is the centre 66/108 of
the canvas — everything meaningful stays inside it, a lesson a sibling app
learned after four icon drafts were eaten by launcher masks.
"""

from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "android" / "app" / "src" / "main" / "res"

BACKGROUND = "#00695C"
CARD = "#FFFFFF"
CHIP = "#E6C36A"
CHIP_LINE = "#B08C3E"

# Geometry in the 108x108 adaptive viewport. Card: 34 wide, 46 tall,
# centred; the cut corner is 11 units; all inside the 66-unit safe circle.
CARD_L, CARD_T, CARD_R, CARD_B = 37.0, 31.0, 71.0, 77.0
CUT = 11.0
RADIUS = 5.0
CHIP_L, CHIP_T, CHIP_R, CHIP_B = 45.0, 48.0, 63.0, 62.0
CHIP_RADIUS = 2.5


def card_path() -> str:
    l, t, r, b = CARD_L, CARD_T, CARD_R, CARD_B
    rad, cut = RADIUS, CUT
    return (
        f"M{l + rad},{t} "
        f"L{r - cut},{t} L{r},{t + cut} "
        f"L{r},{b - rad} Q{r},{b} {r - rad},{b} "
        f"L{l + rad},{b} Q{l},{b} {l},{b - rad} "
        f"L{l},{t + rad} Q{l},{t} {l + rad},{t} Z"
    )


def chip_path() -> str:
    l, t, r, b = CHIP_L, CHIP_T, CHIP_R, CHIP_B
    rad = CHIP_RADIUS
    return (
        f"M{l + rad},{t} L{r - rad},{t} Q{r},{t} {r},{t + rad} "
        f"L{r},{b - rad} Q{r},{b} {r - rad},{b} "
        f"L{l + rad},{b} Q{l},{b} {l},{b - rad} "
        f"L{l},{t + rad} Q{l},{t} {l + rad},{t} Z"
    )


def chip_lines() -> list[str]:
    """Grid strokes over the chip, as thin filled rects (vector strokes at
    this scale render inconsistently across OEM launchers)."""
    w = 0.8
    thirds_x = [CHIP_L + (CHIP_R - CHIP_L) / 3, CHIP_L + 2 * (CHIP_R - CHIP_L) / 3]
    mid_y = (CHIP_T + CHIP_B) / 2
    paths = []
    for x in thirds_x:
        paths.append(
            f"M{x - w / 2},{CHIP_T} h{w} V{CHIP_B} h-{w} Z"
        )
    paths.append(
        f"M{CHIP_L},{mid_y - w / 2} H{CHIP_R} v{w} H{CHIP_L} Z"
    )
    return paths


def vector_xml(card: str, chip: str, monochrome: bool) -> str:
    card_color = "#FFFFFF" if monochrome else CARD
    chip_color = "#FFFFFF" if monochrome else CHIP
    line_color = "#000000" if monochrome else CHIP_LINE
    lines = "".join(
        f'\n    <path android:fillColor="{line_color}" android:pathData="{p}"/>'
        for p in chip_lines()
    )
    # In the monochrome icon the chip must not be drawn as a filled block the
    # same colour as the card, or it disappears; the grid lines carve it out.
    chip_block = (
        ""
        if monochrome
        else f'\n    <path android:fillColor="{chip_color}" android:pathData="{chip}"/>'
    )
    if monochrome:
        # Card silhouette with the chip punched out via even-odd fill.
        return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_icons.py; edit that, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="{card_color}"
        android:fillType="evenOdd"
        android:pathData="{card} {chip}"/>
</vector>
"""
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_icons.py; edit that, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:fillColor="{card_color}" android:pathData="{card}"/>{chip_block}{lines}
</vector>
"""


def draw_raster(size: int, full_bleed: bool) -> Image.Image:
    """Rasterises the same geometry. full_bleed draws edge-to-edge colour
    (Play icon, which Google masks itself); otherwise a rounded square
    (legacy launcher icon)."""
    scale = 8  # supersample for clean edges
    s = size * scale
    unit = s / 108.0
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)

    if full_bleed:
        draw.rectangle([0, 0, s, s], fill=BACKGROUND)
    else:
        draw.rounded_rectangle([0, 0, s - 1, s - 1], radius=int(s * 0.18), fill=BACKGROUND)

    # Legacy and Play icons are not masked as deep as adaptive ones, so the
    # safe-zone-sized art would look lost; zoom it around the centre.
    zoom = 1.3

    def u(v: float) -> float:
        return ((v - 54.0) * zoom + 54.0) * unit

    # Card body: rounded rect then overpaint the cut corner.
    draw.rounded_rectangle(
        [u(CARD_L), u(CARD_T), u(CARD_R), u(CARD_B)],
        radius=RADIUS * zoom * unit,
        fill=CARD,
    )
    draw.polygon(
        [
            (u(CARD_R - CUT), u(CARD_T)),
            (u(CARD_R), u(CARD_T)),
            (u(CARD_R), u(CARD_T + CUT)),
        ],
        fill=BACKGROUND,
    )

    # Chip and its grid.
    draw.rounded_rectangle(
        [u(CHIP_L), u(CHIP_T), u(CHIP_R), u(CHIP_B)],
        radius=CHIP_RADIUS * zoom * unit,
        fill=CHIP,
    )
    # A length, not a coordinate — must not go through the recentring in u().
    line_w = max(int(0.8 * zoom * unit), 1)
    for frac in (1 / 3, 2 / 3):
        x = u(CHIP_L + (CHIP_R - CHIP_L) * frac)
        draw.line([(x, u(CHIP_T)), (x, u(CHIP_B))], fill=CHIP_LINE, width=line_w)
    mid_y = u((CHIP_T + CHIP_B) / 2)
    draw.line([(u(CHIP_L), mid_y), (u(CHIP_R), mid_y)], fill=CHIP_LINE, width=line_w)

    return img.resize((size, size), Image.LANCZOS)


def main() -> None:
    # Vectors.
    drawable = RES / "drawable"
    drawable.mkdir(exist_ok=True)
    (drawable / "ic_launcher_foreground.xml").write_text(
        vector_xml(card_path(), chip_path(), monochrome=False)
    )
    (drawable / "ic_launcher_monochrome.xml").write_text(
        vector_xml(card_path(), chip_path(), monochrome=True)
    )

    values = RES / "values"
    (values / "ic_launcher_background.xml").write_text(
        f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_icons.py; edit that, not this file. -->
<resources>
    <color name="ic_launcher_background">{BACKGROUND}</color>
</resources>
"""
    )

    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(exist_ok=True)
    (anydpi / "ic_launcher.xml").write_text(
        """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_icons.py; edit that, not this file.

     Adaptive icon, Android 8.0+. The background is a flat colour and the
     foreground a vector, so every launcher shape - circle, squircle, rounded
     square, teardrop - masks the ground and leaves the art alone. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""
    )

    # Legacy rasters, API < 26.
    for dpi, size in [("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)]:
        out = RES / f"mipmap-{dpi}" / "ic_launcher.png"
        out.parent.mkdir(exist_ok=True)
        draw_raster(size, full_bleed=False).save(out)

    # Play Store listing icon: 512, full bleed, no transparency.
    play = draw_raster(512, full_bleed=True).convert("RGB")
    play.save(ROOT / "tool" / "play_store_icon.png")

    # Preview through a circular mask, the harshest launcher shape.
    preview = draw_raster(512, full_bleed=True)
    mask = Image.new("L", (512, 512), 0)
    ImageDraw.Draw(mask).ellipse([0, 0, 512, 512], fill=255)
    round_preview = Image.new("RGBA", (512, 512), (0, 0, 0, 0))
    round_preview.paste(preview, (0, 0), mask)
    round_preview.save(ROOT / "tool" / "icon_preview.png")

    print("done")


if __name__ == "__main__":
    main()
